name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'

      - name: dependencies
        working-directory: project
        run: |
          echo ">>> BEGIN sync dependencies"
          uv sync
          echo ">>> END sync dependencies"

      - name: mypy
        working-directory: project
        run: |
          echo ">>> BEGIN mypy compile"
          uv run mypy ../src/ --ignore-missing-imports
          echo ">>> END mypy compile"

      - name: pytest
        working-directory: project
        run: |
          echo ">>> BEGIN pytest"
          uv run pytest ../src/pytest.py
          echo ">>> END pytest"

      - name: run
        working-directory: project
        run: |
          echo ">>> BEGIN program run"
          uv run python ../src/main.py
          echo ">>> END program run"